import Head from "next/head";
import { Inter } from "@next/font/google";
import styled from "styled-components";
import banner from "../images/banner.jpeg";
const inter = Inter({ subsets: ["latin"] });

const Banner = styled.section`
  background: linear-gradient(
      0deg,
      rgba(0, 0, 0, 0.7),
      rgba(120, 120, 120, 0.3)
    ),
    url(${banner.src});
  background-size: cover;
  background-position: center center;
  background-attachment: fixed;
  width: 100%;
  min-height: 100vh;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Iuri Team - Escola de Jiu-jitsu, Jiu-jitsu Infantil e Boxe
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner>
          <button>Agende sua aula experimental agora!</button>
        </Banner>
        <section>
          <p>
            A nossa sede fica localizada na Zona Norte de Porto Alegre, próximo
            ao Bourbon da Assis Brasil.
          </p>
          <p>
            Nós temos treinos KIDS (infantil) em horários alternativos. Para
            crianças a partir de 5 anos de idade.
          </p>
          <p>
            Treinos para adultos de todas as idades (iniciante, intermerdiário,
            avançado e competição).
          </p>
        </section>
      </main>
    </>
  );
}
